import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { CSPostHogProvider } from "~/lib/providers";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Navbar from "~/components/Navbar";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html
            lang="en"
            className={`${GeistSans.variable}`}>
            <ClerkProvider>
                <CSPostHogProvider>
                    <body className="flex h-dvh flex-col">
                        <Navbar />
                        <div className="flex flex-1">{children}</div>
                    </body>
                </CSPostHogProvider>
            </ClerkProvider>
        </html>
    );
}
