import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { clerkClient, currentUser } from '@clerk/nextjs/server';
import { CSPostHogProvider } from "~/providers";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from 'antd'
import { type Metadata } from "next";
import Navbar from "~/app/_components/navbar";
import { defaultTheme } from '~/styles/theme'

export const metadata: Metadata = {
  title: "Compassionate Care Reaching yoU",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // const user = await currentUser()
  // if (user && !user.privateMetadata.isConfigured) {
  //   console.log('User not configured.')
  //   await clerkClient.users.updateUserMetadata(user.id, {
  //     privateMetadata: {
  //       "isConfigured": true,
  //       "role": "member",
  //       "permissions": {
  //         "events": {
  //           "create-new": false
  //         }
  //       }
  //     }
  //   })
  // }

  return (
    <html lang="en">
      <ClerkProvider>
        <CSPostHogProvider>
          <AntdRegistry>
            <ConfigProvider theme={defaultTheme}>
              <body className="flex flex-col h-dvh">
                <Navbar />
                <div className="flex flex-1">{children}</div>
              </body>
            </ConfigProvider>
          </AntdRegistry>
        </CSPostHogProvider>
      </ClerkProvider>
    </html>
  );
}
